language: java
sudo: true
jdk:
  - openjdk15

services:
  - docker

install: true

addons:
  ssh_known_hosts: 185.22.152.167

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD http://185.22.152.167:5000
  - docker build -t 185.22.152.167:5000/bot-image telegram-bot/.
  - docker push 185.22.152.167:5000/bot-image:latest
  - ssh root@185.22.152.167 docker stop tg-bot
  - ssh root@185.22.152.167 docker rm tg-bot
  - ssh root@185.22.152.167 docker pull 185.22.152.167:5000/bot-image
  - ssh root@185.22.152.167 docker run -d --name tg-bot 185.22.152.167:5000/bot-image

script: mvn -pl telegram-bot clean install -DskipTests -Dlogin=lev -Ddb=srabot -Dhost=46.17.47.80
  -Dport=5432 -Dpassword=oU88hY33B75HHnd -P codegen

before_install:
  - "sudo cat /etc/docker/daemon.json | jq '. + {\"insecure-registries\": [\"172.30.0.0:5000\"]}' | sudo tee /etc/docker/daemon.json"
  - sudo cat /etc/docker/deamon.json
  - sudo service docker restart
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
