language: java
sudo: true
jdk:
  - openjdk15

services:
  - docker

install: true

branches:
  only:
    - master

addons:
  ssh_known_hosts: 185.22.152.167

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t webjavalion/tgbot:latest telegram-bot/.
  - docker push webjavalion/tgbot:latest
  - ssh root@185.22.152.167 docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - ssh root@185.22.152.167 docker stop tg-bot
  - ssh root@185.22.152.167 docker rm tg-bot
  - ssh root@185.22.152.167 docker pull webjavalion/tgbot:latest
  - ssh root@185.22.152.167 docker run --env BD_URL=$BD_URL --env BD_USERNAME=$BD_USERNAME --env DRIVER=$DRIVER --env BD_PASSWORD=$BD_PASSWORD
    --env BOT_USER_NAME=$BOT_USER_NAME --env BOT_TOKEN=$BOT_TOKEN -d --name tg-bot webjavalion/tgbot:latest

script: mvn -pl telegram-bot clean install -DskipTests -Dlogin=lev -Ddb=srabot -Dhost=46.17.47.80
  -Dport=5432 -Dpassword=oU88hY33B75HHnd -P codegen

before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
