version: "3"
services:
  service-discovery:
    image: discovery
    ports:
      - 8761:8761
  postgres:
    image: postgres:11.9-alpine
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=srabot
  bot:
    build:
      context: telegram-bot
    container_name: tgbot
    ports:
      - 9062:9062
    environment:
      - BD_URL=-Dapp.jdbcUrl=jdbc:postgresql://postgres:5432/srabot
      - BD_USERNAME=-Dapp.username=root
      - BD_PASSWORD=-Dapp.password=root
      - DRIVER=-Dapp.driver-class-name=org.postgresql.Driver
      - BOT_USERNAME=-Dbot.botUsername=JobGetterBot
      - BOT_TOKEN=-Dbot.botToken=1521711107:AAHqSY66XhtfDd0-2d4k7IuPXAA--TginW4
      - PROFILE=-Dspring.profiles.active=dev
    depends_on:
      - postgres
  stealerBd:
    image: postgres:11.9-alpine
    container_name: stealerBd
    expose:
      - 5000
    ports:
      - 5000:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=vacancy
  stealer:
    image: stealer
    depends_on:
      - stealerBd
    ports:
      - 3067:3067
    environment:
      - API_HASH=-Dapi-hash=-
      - API_ID=-Dapi-id=-
      - PROFILE=-Dspring.profiles.active=compose